name: Upload to Another Repository
on:
  push:
    branches: 
      - master
  # release:
  #   types: [published]
    
jobs:
  remote-upload:
   name: Upload PDF file to Another Repository
   # needs: build
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup git repogitories
        env:
          GH_REPO_DEPLOY_KEY: ${{ secrets.GH_REPO_DEPLOY_KEY }}
          GIT_SSH_COMMAND: ssh -i ./deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          pwd
          # echo "${GH_REPO_DEPLOY_KEY}" > ./deploy_key.pem
          # chmod 600 ./deploy_key.pem
          # git config --global pull.rebase false
          # git config --global user.name "Zero-Trust"
          # git config --global user.email "62760177+Zero-Trust@users.noreply.github.com"
          # git clone origin master
          # cd pdf
          # git checkout master
          # git config remote.origin.url "git@github.com:Zero-Trust/pdf.git"
          # pwd
          
      - name: Get file
        run: |
          touch main.pdf
          echo "this is test" > main.pdf
          
#       - name: Commit to Another Repository
#         env:
#           GIT_SSH_COMMAND: ssh -i ./deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
#         run: |
#           git add -A
#           if ! git diff --cached --quiet; then
#             git commit -m "Deploy ${GITHUB_SHA} by GitHub Actions"
#             git pull origin master
#             git push origin master
#           fi
#           rm ./deploy_key.pem
