name: Upload to Another Repository
on:
  push:
    branches: 
      - master
  # release:
  #   types: [published]
    
jobs:
  remote-upload:
   name: Upload PDF file to Another Repository
   # needs: build
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup git repogitories
        env:
          GH_REPO_DEPLOY_KEY: ${{ secrets.GH_REPO_DEPLOY_KEY }}
          GIT_SSH_COMMAND: ssh -i ./deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          echo "${GH_REPO_DEPLOY_KEY}" > ./deploy_key.pem
          chmod 600 ./deploy_key.pem
          git config --global pull.rebase false
          git config --global user.name "Zero-Trust"
          git config --global user.email "62760177+Zero-Trust@users.noreply.github.com"
          # git clone https://github.com/Zero-Trust/pdf.git
          # cd pdf
          # git checkout master
          # git config remote.origin.url "git@github.com:Zero-Trust/pdf.git"
          pwd
          git submodule add https://github.com/Zero-Trust/pdf.git
          
      - name: Get file
        run: |
          cd pdf/
          git config -l
          touch main.pdf
          echo "this is test" > main.pdf
          echo "This is test" > Notes/test.txt
          git add main.pdf
          git add Notes/test.txt
          echo "***** Get file *****"
          pwd
          ls -l
          echo "***** Get file *****"
          
      - name: Commit to Another Repository
        env:
          GH_REPO_DEPLOY_KEY: ${{ secrets.GH_REPO_DEPLOY_KEY }}
          GIT_SSH_COMMAND: ssh -i ./deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        run: |
          # origin=https://${GITHUB_ACTOR}:${API_GITHUB_TOKEN}@github.com/Zero-Trust/pdf.git
          # origin=https://{API_GITHUB_TOKEN}:x-oauth-basic@github.com/Zero-Trust/pdf.git
          origin=https://x-access-token:{API_GITHUB_TOKEN}@github.com/Zero-Trust/pdf.git
          cd pdf/
          echo "**** 2 ****"
          git config -l
          echo "**** 2 ****"
          git pull $origin master
          git add .
          git commit -m "Deploy ${GITHUB_SHA} by GitHub Actions"
          git push $origin master
          
#           git add -A
#           if ! git diff --cached --quiet; then
#             git commit -m "Deploy ${GITHUB_SHA} by GitHub Actions"
#             git pull origin master
#             git push origin master
#           fi
      - name: clean-up
        run: |
          echo "***** clean up *****"
          pwd
          ls -l ./pdf
          echo "***** clean up *****"
          # cd ..
          git submodule deinit --all
          git rm pdf
          git rm --cached .gitmodules && rm .gitmodules
          git status
          pwd
          
